name:                nspace
version:             0.1.0.0
github:              "isovector/nspace"
license:             BSD-3-Clause
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2023 Sandy Maguire"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Efficient, infinite-precision 2D and 3D spatial containers.
category:            Data Structures

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/nspace#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- linear
- monoidal-containers
- hashable

default-extensions:
- BangPatterns
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- GeneralisedNewtypeDeriving
- ImplicitPrelude
- LambdaCase
- MonomorphismRestriction
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- StarIsType
- TypeApplications
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  nspace-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - hspec-discover >= 2.0
    dependencies:
    - nspace
    - hspec
    - QuickCheck
    - checkers
